# Generated by Django 3.1.4 on 2020-12-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('current_amount', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
