# Generated by Django 3.0.3 on 2020-12-30 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_service', '0003_loan_last_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='last_payment_date',
            field=models.DateField(default=datetime.date(2020, 12, 30)),
        ),
    ]
