# Generated by Django 3.1.4 on 2020-12-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_service', '0004_auto_20201230_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=6),
        ),
    ]
