# Generated by Django 3.1.4 on 2020-12-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_service', '0006_auto_20201230_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlog',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
